path: /data/shared/MSc-Klaudia-Olimpia-Herl/ai_allergenic_tree_species_mapping/data/processed/splits_irrg_seg
train: train/images
val: val/images
test: test/images

nc: 1

names:
    0: Tree

